In [1]:
import tensorflow as tf

In [2]:
images_ds = tf.data.Dataset.list_files('dataset/PlantVillage/*/*', shuffle=False)

In [3]:
for i in images_ds.take(3).as_numpy_iterator():
    print(i)

b'dataset\\PlantVillage\\Potato___Early_blight\\001187a0-57ab-4329-baff-e7246a9edeb0___RS_Early.B 8178.JPG'
b'dataset\\PlantVillage\\Potato___Early_blight\\002a55fb-7a3d-4a3a-aca8-ce2d5ebc6925___RS_Early.B 8170.JPG'
b'dataset\\PlantVillage\\Potato___Early_blight\\009c8c31-f22d-4ffd-8f16-189c6f06c577___RS_Early.B 7885.JPG'


In [10]:
images_ds = images_ds.shuffle(100)
for i in images_ds.take(3).as_numpy_iterator():
    print(i)

b'dataset\\PlantVillage\\Potato___Early_blight\\096a2c48-104c-4570-9e34-8dd60aa5ebcf___RS_Early.B 6979.JPG'
b'dataset\\PlantVillage\\Potato___Early_blight\\08029ccc-387e-4be6-9389-04f7b82fdb2a___RS_Early.B 9130.JPG'
b'dataset\\PlantVillage\\Potato___Early_blight\\585062b6-d5a4-4677-8b7f-773257399423___RS_Early.B 8558.JPG'


In [11]:
class_names = ['early', 'healthy', 'late']

In [14]:
image_Count = len(images_ds)
image_Count

2152

In [20]:
train_size = int(image_Count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [24]:
len(train_ds)

1721

In [23]:
len(test_ds)

431

In [25]:
s = "ataset\\PlantVillage\\Potato___Early_blight\\096a2c48-104c-4570-9e34-8dd60aa5ebcf___RS_Early.B 6979.JPG"

In [30]:
s.split('\\')[2]

'Potato___Early_blight'

In [71]:
import os

In [75]:
def getImageLable(file):
    return tf.strings.split(file, os.path.sep)[2]
   
    

In [76]:
getImageLable(s)

<tf.Tensor: shape=(), dtype=string, numpy=b'Potato___Early_blight'>

In [78]:
for i in train_ds.as_numpy_iterator():
    getImageLable(i)

In [79]:
def processImage(filePath):
    label = getImageLable(filePath)
    
    image = tf.io.read_file(filePath)
    image = tf.image.decode_jpeg(image)
    img = tf.image.resize(image, [128,128])

    return label, image
    

In [81]:
for label,image in train_ds.map(processImage).take(3):
    print(image)
    print(label)

tf.Tensor(
[[[129 134 154]
  [132 137 157]
  [131 136 156]
  ...
  [ 94  95 115]
  [ 98  99 119]
  [102 103 123]]

 [[128 133 153]
  [132 137 157]
  [133 138 158]
  ...
  [ 99 100 120]
  [101 102 122]
  [102 103 123]]

 [[129 134 154]
  [133 138 158]
  [134 139 159]
  ...
  [ 97  98 118]
  [ 96  97 117]
  [ 95  96 116]]

 ...

 [[133 135 148]
  [138 140 153]
  [140 142 155]
  ...
  [ 88  84  98]
  [ 92  88 102]
  [ 99  95 109]]

 [[134 136 149]
  [140 142 155]
  [143 145 158]
  ...
  [ 89  85 100]
  [ 73  69  84]
  [ 73  69  84]]

 [[139 141 154]
  [144 146 159]
  [145 147 160]
  ...
  [108 104 119]
  [100  96 111]
  [ 94  90 105]]], shape=(256, 256, 3), dtype=uint8)
tf.Tensor(b'Potato___Early_blight', shape=(), dtype=string)
tf.Tensor(
[[[101 103 116]
  [102 104 117]
  [103 105 118]
  ...
  [155 156 174]
  [159 160 178]
  [160 161 179]]

 [[ 95  97 110]
  [ 99 101 114]
  [105 107 120]
  ...
  [164 165 183]
  [162 163 181]
  [159 160 178]]

 [[116 118 131]
  [108 110 123]
  [101 103 11

In [85]:
def scale(image, label):
    return image/255

In [86]:
train_ds = train_ds.map(scale)

TypeError: in user code:


    TypeError: outer_factory.<locals>.inner_factory.<locals>.tf__scale() missing 1 required positional argument: 'label'
